
title: LiteGapps
email: 
description: " "
baseurl: "/"
google_site_verification: 
url: "litegapps.site"
twitter_username: 
github_username: 
author: wahyu678997

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
